# Generated by Django 2.0.1 on 2018-02-20 04:40

from django.db import migrations, models
from util.model_tools import common_upload_path_handler


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetFileTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=100, unique=True, verbose_name='短码')),
                ('type', models.IntegerField(choices=[(1, '图片'), (2, '视频')], default=1, verbose_name='类型')),
            ],
            options={
                'verbose_name': '推文文件中转',
                'verbose_name_plural': '推文文件中转',
                'db_table': 'tweet_file_transfer',
            },
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common_upload_path_handler, verbose_name='图片')),
                ('describe', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '推文图片',
                'verbose_name_plural': '推文图片',
                'db_table': 'tweet_image',
            },
        ),
        migrations.CreateModel(
            name='TweetVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=common_upload_path_handler, verbose_name='视频')),
                ('describe', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '推文视频',
                'verbose_name_plural': '推文视频',
                'db_table': 'tweet_video',
            },
        ),
        migrations.AddField(
            model_name='tweetfiletransfer',
            name='images',
            field=models.ManyToManyField(blank=True, to='medium.TweetImage', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='tweetfiletransfer',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='medium.TweetVideo', verbose_name='视频'),
        ),
    ]
