# Generated by Django 2.0.1 on 2018-02-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetfiletransfer',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medium.TweetVideo', verbose_name='视频'),
        ),
    ]
