# Generated by Django 2.0.1 on 2018-01-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='文字')),
                ('short_code', models.CharField(max_length=100, unique=True, verbose_name='短码')),
                ('type', models.IntegerField(choices=[(1, '图片'), (2, '视频')], default=1, verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '发文',
                'verbose_name_plural': '发文',
                'db_table': 'tweet',
            },
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='图片')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'tweet_image',
            },
        ),
        migrations.CreateModel(
            name='TweetVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='视频')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'tweet_video',
            },
        ),
        migrations.AddField(
            model_name='tweet',
            name='images',
            field=models.ManyToManyField(to='tweet.TweetImage', verbose_name='图片'),
        ),
    ]
