# Generated by Django 2.0.1 on 2018-02-01 13:49

from django.conf import settings
from django.db import migrations, models
import util.model_tools.file_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='文字')),
                ('short_code', models.CharField(max_length=100, unique=True, verbose_name='短码')),
                ('type', models.IntegerField(choices=[(1, '图片'), (2, '视频')], default=1, verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '推文',
                'verbose_name_plural': '推文',
                'db_table': 'tweet',
            },
        ),
        migrations.CreateModel(
            name='TweetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=util.model_tools.file_upload.common_upload_path_handler, verbose_name='图片')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '推文图片',
                'verbose_name_plural': '推文图片',
                'db_table': 'tweet_image',
            },
        ),
        migrations.CreateModel(
            name='TweetVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='视频')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '推文视频',
                'verbose_name_plural': '推文视频',
                'db_table': 'tweet_video',
            },
        ),
        migrations.AddField(
            model_name='tweet',
            name='images',
            field=models.ManyToManyField(blank=True, to='tweet.TweetImage', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='tweet.TweetVideo', verbose_name='视频'),
        ),
    ]
