# Generated by Django 2.0.1 on 2018-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetimage',
            name='describe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tweetvideo',
            name='describe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
    ]
