# Generated by Django 2.0.1 on 2018-02-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0001_initial'),
        ('tweet', '0002_auto_20180220_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_image_thumbnail', to='medium.TweetImage', verbose_name='略缩展示图'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='tweet_image', to='medium.TweetImage', verbose_name='图片'),
        ),
    ]
