# Generated by Django 2.0.1 on 2018-02-08 08:30

from django.db import migrations, models
import util.model_tools.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20180203_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetFileTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=100, unique=True, verbose_name='短码')),
                ('type', models.IntegerField(choices=[(1, '图片'), (2, '视频')], default=1, verbose_name='类型')),
                ('images', models.ManyToManyField(blank=True, to='tweet.TweetImage', verbose_name='图片')),
            ],
            options={
                'verbose_name': '推文文件中转',
                'verbose_name_plural': '推文文件中转',
                'db_table': 'tweet_file_transfer',
            },
        ),
        migrations.AlterField(
            model_name='tweetvideo',
            name='video',
            field=models.FileField(upload_to=util.model_tools.file_upload.common_upload_path_handler, verbose_name='视频'),
        ),
        migrations.AddField(
            model_name='tweetfiletransfer',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='tweet.TweetVideo', verbose_name='视频'),
        ),
    ]
