# Generated by Django 2.0.1 on 2018-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20180208_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetfiletransfer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='tweetfiletransfer',
            name='video',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='images',
            field=models.ManyToManyField(blank=True, to='medium.TweetImage', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='medium.TweetVideo', verbose_name='视频'),
        ),
        migrations.DeleteModel(
            name='TweetFileTransfer',
        ),
        migrations.DeleteModel(
            name='TweetImage',
        ),
        migrations.DeleteModel(
            name='TweetVideo',
        ),
    ]
