# Generated by Django 2.0.1 on 2018-02-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20180212_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-update_time', '-create_time'), 'verbose_name': '推文', 'verbose_name_plural': '推文'},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medium.TweetVideo', verbose_name='视频'),
        ),
    ]
