# Generated by Django 2.0.1 on 2018-01-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('first_name', models.CharField(max_length=10, verbose_name='姓')),
                ('last_name', models.CharField(max_length=10, verbose_name='名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('phone', models.IntegerField(blank=True, null=True, unique=True, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '注册',
                'verbose_name_plural': '注册',
                'db_table': 'regist',
            },
        ),
    ]
