# Generated by Django 2.0.1 on 2018-02-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '推文评论',
                'verbose_name_plural': '推文评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='CommentSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文字')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论标记',
                'verbose_name_plural': '评论标记',
                'db_table': 'comment_sign',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=7, verbose_name='周期(day)')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='PersonRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_follow', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否关注')),
                ('is_block', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否屏蔽')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '人物关系',
                'verbose_name_plural': '人物关系',
                'db_table': 'person_relations',
            },
        ),
        migrations.CreateModel(
            name='TweetRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否点赞')),
                ('is_collect', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否收藏')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '推文关系',
                'verbose_name_plural': '推文关系',
                'db_table': 'tweet_relations',
            },
        ),
        migrations.CreateModel(
            name='TweetSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文字')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '推文标记',
                'verbose_name_plural': '推文标记',
                'db_table': 'tweet_sign',
            },
        ),
    ]
