# Generated by Django 2.0.1 on 2018-02-01 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('tweet', models.ForeignKey(on_delete='SET_NULL', to='tweet.Tweet', verbose_name='被评论文章')),
                ('user', models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '推文评论',
                'verbose_name_plural': '推文评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='PersonRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_block', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否屏蔽')),
                ('is_friend', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否关注')),
                ('act_one', models.ForeignKey(on_delete='SET_NULL', related_name='act_person', to=settings.AUTH_USER_MODEL, verbose_name='行为方')),
                ('target_one', models.ForeignKey(on_delete='SET_NULL', related_name='target_person', to=settings.AUTH_USER_MODEL, verbose_name='目标')),
            ],
            options={
                'verbose_name': '人物关系',
                'verbose_name_plural': '人物关系',
                'db_table': 'person_relations',
            },
        ),
        migrations.CreateModel(
            name='TweetRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('is_like', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否点赞')),
                ('is_collect', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否收藏')),
                ('tweet', models.ForeignKey(on_delete='SET_NULL', to='tweet.Tweet', verbose_name='收藏文章')),
                ('user', models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '推文关系',
                'verbose_name_plural': '推文关系',
                'db_table': 'tweet_relations',
            },
        ),
        migrations.CreateModel(
            name='TweetSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文字')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('act_one', models.ForeignKey(on_delete='SET_NULL', related_name='sign_act_person', to=settings.AUTH_USER_MODEL, verbose_name='行为方')),
                ('target_one', models.ForeignKey(on_delete='SET_NULL', related_name='sign_target_person', to=settings.AUTH_USER_MODEL, verbose_name='目标')),
                ('tweet', models.ForeignKey(on_delete='SET_NULL', to='tweet.Tweet', verbose_name='文章')),
            ],
            options={
                'verbose_name': '推文标记',
                'verbose_name_plural': '推文标记',
                'db_table': 'tweet_sign',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tweetrelations',
            unique_together={('user', 'tweet')},
        ),
        migrations.AlterUniqueTogether(
            name='personrelations',
            unique_together={('act_one', 'target_one')},
        ),
    ]
