# Generated by Django 2.0.1 on 2018-01-27 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsign',
            name='act_one',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='sign_act_person', to=settings.AUTH_USER_MODEL, verbose_name='行为方'),
        ),
        migrations.AddField(
            model_name='tweetsign',
            name='target',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='sign_target_person', to=settings.AUTH_USER_MODEL, verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='tweetsign',
            name='tweet',
            field=models.ForeignKey(on_delete='SET_NULL', to='tweet.Tweet', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='personrelations',
            name='act_one',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='act_person', to=settings.AUTH_USER_MODEL, verbose_name='行为方'),
        ),
        migrations.AddField(
            model_name='personrelations',
            name='target_one',
            field=models.ForeignKey(on_delete='SET_NULL', related_name='target_person', to=settings.AUTH_USER_MODEL, verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete='SET_NULL', to='tweet.Tweet', verbose_name='被评论文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
    ]
