# Generated by Django 2.0.1 on 2018-02-20 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweet', '0001_initial'),
        ('relation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetsign',
            name='act_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_sign_act_person', to=settings.AUTH_USER_MODEL, verbose_name='行为方'),
        ),
        migrations.AddField(
            model_name='tweetsign',
            name='target_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_sign_target_person', to=settings.AUTH_USER_MODEL, verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='tweetsign',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='tweetrelations',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet', verbose_name='收藏文章'),
        ),
        migrations.AddField(
            model_name='tweetrelations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
        migrations.AddField(
            model_name='personrelations',
            name='act_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_person', to=settings.AUTH_USER_MODEL, verbose_name='行为方'),
        ),
        migrations.AddField(
            model_name='personrelations',
            name='target_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_person', to=settings.AUTH_USER_MODEL, verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='notice',
            name='commentSigns',
            field=models.ManyToManyField(blank=True, to='relation.CommentSign', verbose_name='评论标记'),
        ),
        migrations.AddField(
            model_name='notice',
            name='comments',
            field=models.ManyToManyField(blank=True, to='relation.Comment', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='notice',
            name='personFollows',
            field=models.ManyToManyField(blank=True, to='relation.PersonRelations', verbose_name='person follow'),
        ),
        migrations.AddField(
            model_name='notice',
            name='tweetLikes',
            field=models.ManyToManyField(blank=True, to='relation.TweetRelations', verbose_name='tweet点赞'),
        ),
        migrations.AddField(
            model_name='notice',
            name='tweetSigns',
            field=models.ManyToManyField(blank=True, to='relation.TweetSign', verbose_name='tweet标记'),
        ),
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='commentsign',
            name='act_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_sign_act_person', to=settings.AUTH_USER_MODEL, verbose_name='行为方'),
        ),
        migrations.AddField(
            model_name='commentsign',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation.Comment', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='commentsign',
            name='target_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_sign_target_person', to=settings.AUTH_USER_MODEL, verbose_name='目标'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet', verbose_name='被评论文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterUniqueTogether(
            name='tweetrelations',
            unique_together={('user', 'tweet')},
        ),
        migrations.AlterUniqueTogether(
            name='personrelations',
            unique_together={('act_one', 'target_one')},
        ),
    ]
