# Generated by Django 2.0.1 on 2018-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetrelations',
            name='is_collect',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否收藏'),
        ),
        migrations.AlterField(
            model_name='tweetrelations',
            name='is_like',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否点赞'),
        ),
    ]
