# Generated by Django 2.0.1 on 2018-02-20 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0002_auto_20180220_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notices',
        ),
        migrations.AlterModelTable(
            name='notices',
            table='notices',
        ),
    ]
