# Generated by Django 2.0.1 on 2018-02-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_auto_20180220_1241'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notices',
            table='notice',
        ),
    ]
