# Generated by Django 2.0.1 on 2018-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0004_auto_20180220_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='tweetCollects',
            field=models.ManyToManyField(blank=True, related_name='notices_tweet_collect', to='relation.TweetRelations', verbose_name='tweet收藏'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='tweetLikes',
            field=models.ManyToManyField(blank=True, related_name='notices_tweet_like', to='relation.TweetRelations', verbose_name='tweet点赞'),
        ),
    ]
