# Generated by Django 2.0.1 on 2018-02-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relation', '0006_auto_20180219_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentSign', models.ManyToManyField(blank=True, to='relation.CommentSign', verbose_name='评论标记')),
                ('PersonRelations', models.ManyToManyField(blank=True, to='relation.PersonRelations', verbose_name='person关系')),
                ('TweetRelations', models.ManyToManyField(blank=True, to='relation.TweetRelations', verbose_name='tweet关系')),
                ('TweetSign', models.ManyToManyField(blank=True, to='relation.TweetSign', verbose_name='tweet标记')),
                ('comments', models.ManyToManyField(blank=True, to='relation.Comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notice',
            },
        ),
    ]
