# Generated by Django 2.0.1 on 2018-02-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0007_notices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notices',
            old_name='CommentSign',
            new_name='CommentSigns',
        ),
        migrations.RenameField(
            model_name='notices',
            old_name='PersonRelations',
            new_name='PersonFollows',
        ),
        migrations.RenameField(
            model_name='notices',
            old_name='TweetRelations',
            new_name='TweetLikes',
        ),
        migrations.RenameField(
            model_name='notices',
            old_name='TweetSign',
            new_name='TweetSigns',
        ),
    ]
