# Generated by Django 2.0.1 on 2018-02-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0008_auto_20180220_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notices',
            old_name='CommentSigns',
            new_name='commentSigns',
        ),
        migrations.RenameField(
            model_name='notices',
            old_name='PersonFollows',
            new_name='personFollows',
        ),
        migrations.RenameField(
            model_name='notices',
            old_name='TweetLikes',
            new_name='tweetLikes',
        ),
        migrations.RenameField(
            model_name='notices',
            old_name='TweetSigns',
            new_name='tweetSigns',
        ),
    ]
